package zotmc.chikuwabu.data;

import zotmc.chikuwabu.util.Utils.Dependency;
import zotmc.chikuwabu.util.Utils.Modid;
import zotmc.chikuwabu.util.Utils.Requirements;

import com.google.common.collect.Lists;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModMetadata;

@Requirements("1.7 = 1.7")
public class ModData {
	
	public static class Chikuwabus {
		public static final String
		MODID = "chikuwabu",
		NAME = "Chikuwabu",
		MC_STRING = Loader.MC_VERSION,
		VERSION = "1.0.0.0-" + MC_STRING;
	}
	
	public static void init(ModMetadata metadata) {
		metadata.autogenerated = false;
		metadata.authorList = Lists.newArrayList("Zot");
		metadata.description = "Chikuwabu desu.";
	}
	
	
	@Dependency
	@Requirements({"1.7.10 = 10.13.0.1207", "1.7.2 = 10.12.2.1121"})
	public static class Forge {
		@Modid public static final String MODID = "Forge";
	}
	
}
